/* tslint:disable */

/* eslint-disable */

/**
 * Social Network API
 * API for a social network service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DefaultApi } from './api';
import { Configuration } from './configuration';

const config = new Configuration({
  basePath: `${import.meta.env.VITE_APP_URL}:${import.meta.env.VITE_APP_PORT}`,
});

export const api = new DefaultApi(config);
