/* tslint:disable */
/* eslint-disable */
/**
 * Social Network API
 * API for a social network service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Channel
 */
export interface Channel {
  /**
   *
   * @type {boolean}
   * @memberof Channel
   */
  authRequired: boolean;
  /**
   *
   * @type {Array<string>}
   * @memberof Channel
   */
  posts: Array<string>;
  /**
   *
   * @type {string}
   * @memberof Channel
   */
  _id: string;
  /**
   *
   * @type {string}
   * @memberof Channel
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof Channel
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof Channel
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof Channel
   */
  updatedAt: string;
}
