/* tslint:disable */
/* eslint-disable */
/**
 * Social Network API
 * API for a social network service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const CreateNotificationRequestNotificationTypeEnum = {
  COMMENT: 'COMMENT',
  FOLLOW: 'FOLLOW',
  LIKE: 'LIKE',
  MESSAGE: 'MESSAGE',
} as const;

export type CreateNotificationRequestNotificationType =
  (typeof CreateNotificationRequestNotificationTypeEnum)[keyof typeof CreateNotificationRequestNotificationTypeEnum];
/**
 *
 * @export
 * @interface CreateNotificationRequest
 */
export interface CreateNotificationRequest {
  /**
   *
   * @type {string}
   * @memberof CreateNotificationRequest
   */
  notificationType: CreateNotificationRequestNotificationType;
  /**
   *
   * @type {string}
   * @memberof CreateNotificationRequest
   */
  notificationTypeId: string;
  /**
   *
   * @type {string}
   * @memberof CreateNotificationRequest
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof CreateNotificationRequest
   */
  postId: string | null;
}
