/* tslint:disable */
/* eslint-disable */
/**
 * Social Network API
 * API for a social network service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const CreateNotificationRequestNotificationTypeEnumEnum = {
  Comment: 'COMMENT',
  Follow: 'FOLLOW',
  Like: 'LIKE',
  Message: 'MESSAGE',
} as const;

export type CreateNotificationRequestNotificationTypeEnum =
  (typeof CreateNotificationRequestNotificationTypeEnumEnum)[keyof typeof CreateNotificationRequestNotificationTypeEnumEnum];
/**
 *
 * @export
 * @interface CreateNotificationRequest
 */
export interface CreateNotificationRequest {
  /**
   *
   * @type {string}
   * @memberof CreateNotificationRequest
   */
  notificationType: CreateNotificationRequestNotificationTypeEnum;
  /**
   *
   * @type {string}
   * @memberof CreateNotificationRequest
   */
  notificationTypeId: string;
  /**
   *
   * @type {string}
   * @memberof CreateNotificationRequest
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof CreateNotificationRequest
   */
  postId: string | null;
}
