/* tslint:disable */
/* eslint-disable */
/**
 * Social Network API
 * API for a social network service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Like
 */
export interface Like {
  /**
   *
   * @type {string}
   * @memberof Like
   */
  _id: string;
  /**
   *
   * @type {string}
   * @memberof Like
   */
  user: string;
  /**
   *
   * @type {string}
   * @memberof Like
   */
  post: string;
  /**
   *
   * @type {string}
   * @memberof Like
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof Like
   */
  updatedAt: string;
}
