/* tslint:disable */

/* eslint-disable */

/**
 * Social Network API
 * API for a social network service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

/**
 *
 * @export
 * @interface Login200Response
 */
export interface Login200Response {
  /**
   *
   * @type {User}
   * @memberof Login200Response
   */
  user: User;
  /**
   *
   * @type {string}
   * @memberof Login200Response
   */
  token: string;
}
