/* tslint:disable */

/* eslint-disable */

/**
 * Social Network API
 * API for a social network service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

/**
 *
 * @export
 * @interface Message
 */
export interface Message {
  /**
   *
   * @type {string}
   * @memberof Message
   */
  _id: string;
  /**
   *
   * @type {string}
   * @memberof Message
   */
  message: string;
  /**
   *
   * @type {User}
   * @memberof Message
   */
  sender: User;
  /**
   *
   * @type {User}
   * @memberof Message
   */
  receiver: User;
  /**
   *
   * @type {boolean}
   * @memberof Message
   */
  seen: boolean;
  /**
   *
   * @type {string}
   * @memberof Message
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof Message
   */
  updatedAt: string;
}
