/* tslint:disable */

/* eslint-disable */

/**
 * Social Network API
 * API for a social network service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { Comment } from './comment';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationUser } from './notification-user';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

/**
 *
 * @export
 * @interface Notification
 */
export interface Notification {
  /**
   *
   * @type {boolean}
   * @memberof Notification
   */
  seen: boolean;
  /**
   *
   * @type {string}
   * @memberof Notification
   */
  _id: string;
  /**
   *
   * @type {User}
   * @memberof Notification
   */
  author: User;
  /**
   *
   * @type {NotificationUser}
   * @memberof Notification
   */
  user?: NotificationUser;
  /**
   *
   * @type {string}
   * @memberof Notification
   */
  post?: string | null;
  /**
   *
   * @type {string}
   * @memberof Notification
   */
  follow?: string;
  /**
   *
   * @type {Comment}
   * @memberof Notification
   */
  comment?: Comment;
  /**
   *
   * @type {string}
   * @memberof Notification
   */
  message?: string;
  /**
   *
   * @type {string}
   * @memberof Notification
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof Notification
   */
  updatedAt: string;
}
