/* tslint:disable */

/* eslint-disable */

/**
 * Social Network API
 * API for a social network service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { Like } from './like';
// May contain unused imports in some cases
// @ts-ignore
import type { Message } from './message';
// May contain unused imports in some cases
// @ts-ignore
import type { Notification } from './notification';
// May contain unused imports in some cases
// @ts-ignore
import type { Post } from './post';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';
// May contain unused imports in some cases
// @ts-ignore
import type { UserFollowingInner } from './user-following-inner';

/**
 * @type NotificationUser
 * @export
 */
export type NotificationUser = User | string;
