/* tslint:disable */

/* eslint-disable */

/**
 * Social Network API
 * API for a social network service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { Channel } from './channel';
// May contain unused imports in some cases
// @ts-ignore
import type { Comment } from './comment';
// May contain unused imports in some cases
// @ts-ignore
import type { Like } from './like';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

/**
 *
 * @export
 * @interface Post
 */
export interface Post {
  /**
   *
   * @type {Array<Like>}
   * @memberof Post
   */
  likes: Array<Like>;
  /**
   *
   * @type {Array<Comment>}
   * @memberof Post
   */
  comments: Array<Comment>;
  /**
   *
   * @type {string}
   * @memberof Post
   */
  _id: string;
  /**
   *
   * @type {string}
   * @memberof Post
   */
  image: string | null;
  /**
   *
   * @type {string}
   * @memberof Post
   */
  imagePublicId: string | null;
  /**
   *
   * @type {string}
   * @memberof Post
   */
  title: string;
  /**
   *
   * @type {Channel}
   * @memberof Post
   */
  channel: Channel;
  /**
   *
   * @type {User}
   * @memberof Post
   */
  author: User;
  /**
   *
   * @type {string}
   * @memberof Post
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof Post
   */
  updatedAt: string;
}
