/* tslint:disable */
/* eslint-disable */
/**
 * Social Network API
 * API for a social network service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SendMessageRequest
 */
export interface SendMessageRequest {
  /**
   *
   * @type {string}
   * @memberof SendMessageRequest
   */
  message: string;
  /**
   *
   * @type {string}
   * @memberof SendMessageRequest
   */
  receiver: string;
}
