/* tslint:disable */
/* eslint-disable */
/**
 * Social Network API
 * API for a social network service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SignupRequest
 */
export interface SignupRequest {
  /**
   *
   * @type {string}
   * @memberof SignupRequest
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof SignupRequest
   */
  fullName?: string;
  /**
   *
   * @type {string}
   * @memberof SignupRequest
   */
  password?: string;
}
