/* tslint:disable */

/* eslint-disable */

/**
 * Social Network API
 * API for a social network service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { Like } from './like';
// May contain unused imports in some cases
// @ts-ignore
import type { Message } from './message';
// May contain unused imports in some cases
// @ts-ignore
import type { Notification } from './notification';
// May contain unused imports in some cases
// @ts-ignore
import type { Post } from './post';
// May contain unused imports in some cases
// @ts-ignore
import type { UserFollowingInner } from './user-following-inner';

/**
 *
 * @export
 * @interface User
 */
export interface User {
  /**
   *
   * @type {string}
   * @memberof User
   */
  coverImage?: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  image?: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  role: string;
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  emailVerified?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  banned?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  isOnline: boolean;
  /**
   *
   * @type {Array<Post>}
   * @memberof User
   */
  posts: Array<Post>;
  /**
   *
   * @type {Array<Like>}
   * @memberof User
   */
  likes: Array<Like>;
  /**
   *
   * @type {Array<string>}
   * @memberof User
   */
  comments: Array<string>;
  /**
   *
   * @type {Array<any>}
   * @memberof User
   */
  followers: Array<any>;
  /**
   *
   * @type {Array<UserFollowingInner>}
   * @memberof User
   */
  following: Array<UserFollowingInner>;
  /**
   *
   * @type {Array<Notification>}
   * @memberof User
   */
  notifications: Array<Notification>;
  /**
   *
   * @type {Array<Message>}
   * @memberof User
   */
  messages: Array<Message>;
  /**
   *
   * @type {string}
   * @memberof User
   */
  _id: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  fullName: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  updatedAt: string;
}
