/* tslint:disable */
/* eslint-disable */
/**
 * Social Network API
 * API for a social network service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserFollowingInner
 */
export interface UserFollowingInner {
  /**
   *
   * @type {string}
   * @memberof UserFollowingInner
   */
  _id?: string;
  /**
   *
   * @type {string}
   * @memberof UserFollowingInner
   */
  user?: string;
  /**
   *
   * @type {string}
   * @memberof UserFollowingInner
   */
  follower?: string;
  /**
   *
   * @type {string}
   * @memberof UserFollowingInner
   */
  createdAt?: string;
  /**
   *
   * @type {string}
   * @memberof UserFollowingInner
   */
  updatedAt?: string;
  /**
   *
   * @type {number}
   * @memberof UserFollowingInner
   */
  __v?: number;
}
